/**
 * Complete Gen 1 Character, Item, Move, Type, Sprite, and Species Lookup Tables.
 * Matches Game Boy Pokémon Red/Blue character and memory specifications.
 */

export const GEN1_CHAR_MAP: Record<number, string> = {
    0x7F: ' ',
    0x80: 'A', 0x81: 'B', 0x82: 'C', 0x83: 'D', 0x84: 'E', 0x85: 'F', 0x86: 'G',
    0x87: 'H', 0x88: 'I', 0x89: 'J', 0x8A: 'K', 0x8B: 'L', 0x8C: 'M', 0x8D: 'N',
    0x8E: 'O', 0x8F: 'P', 0x90: 'Q', 0x91: 'R', 0x92: 'S', 0x93: 'T', 0x94: 'U',
    0x95: 'V', 0x96: 'W', 0x97: 'X', 0x98: 'Y', 0x99: 'Z',
    0x9A: '(', 0x9B: ')', 0x9C: ':', 0x9D: ';', 0x9E: '[', 0x9F: ']',
    0xA0: 'a', 0xA1: 'b', 0xA2: 'c', 0xA3: 'd', 0xA4: 'e', 0xA5: 'f', 0xA6: 'g',
    0xA7: 'h', 0xA8: 'i', 0xA9: 'j', 0xAA: 'k', 0xAB: 'l', 0xAC: 'm', 0xAD: 'n',
    0xAE: 'o', 0xAF: 'p', 0xB0: 'q', 0xB1: 'r', 0xB2: 's', 0xB3: 't', 0xB4: 'u',
    0xB5: 'v', 0xB6: 'w', 0xB7: 'x', 0xB8: 'y', 0xB9: 'z',
    0xBA: 'é', 0xBB: "'d", 0xBC: "'l", 0xBD: "'s", 0xBE: "'t", 0xBF: "'v",
    0xE0: "'", 0xE1: 'PK', 0xE2: 'MN', 0xE3: '-', 0xE4: "'r", 0xE5: "'m",
    0xE6: '?', 0xE7: '!', 0xE8: '.',
    0xED: '▶', 0xEE: '▼', 0xEF: '♂',
    0xF0: '$', 0xF1: '×', 0xF2: '.', 0xF3: '/', 0xF4: ',', 0xF5: '♀',
    0xF6: '0', 0xF7: '1', 0xF8: '2', 0xF9: '3', 0xFA: '4',
    0xFB: '5', 0xFC: '6', 0xFD: '7', 0xFE: '8', 0xFF: '9',
    0x79: '┌', 0x7A: '─', 0x7B: '┐', 0x7C: '│', 0x7D: '└', 0x7E: '┘',
};

export const ITEM_NAMES: Readonly<Record<number, string>> = {
    0x01: 'MASTER BALL',
    0x02: 'ULTRA BALL',
    0x03: 'GREAT BALL',
    0x04: 'POKé BALL',
    0x05: 'TOWN MAP',
    0x06: 'BICYCLE',
    0x07: '???',
    0x08: 'SAFARI BALL',
    0x09: 'POKéDEX',
    0x0A: 'MOON STONE',
    0x0B: 'ANTIDOTE',
    0x0C: 'BURN HEAL',
    0x0D: 'ICE HEAL',
    0x0E: 'AWAKENING',
    0x0F: 'PARLYZ HEAL',
    0x10: 'FULL RESTORE',
    0x11: 'MAX POTION',
    0x12: 'HYPER POTION',
    0x13: 'SUPER POTION',
    0x14: 'POTION',
    0x1D: 'ESCAPE ROPE',
    0x1E: 'REPEL',
    0x1F: 'OLD AMBER',
    0x20: 'FIRE STONE',
    0x21: 'THUNDERSTONE',
    0x22: 'WATER STONE',
    0x23: 'HP UP',
    0x24: 'PROTEIN',
    0x25: 'IRON',
    0x26: 'CARBOS',
    0x27: 'CALCIUM',
    0x28: 'RARE CANDY',
    0x29: 'DOME FOSSIL',
    0x2A: 'HELIX FOSSIL',
    0x2B: 'SECRET KEY',
    0x2C: '???',
    0x2D: 'BIKE VOUCHER',
    0x2E: 'X ACCURACY',
    0x2F: 'LEAF STONE',
    0x30: 'CARD KEY',
    0x31: 'NUGGET',
    0x32: 'PP UP',
    0x33: 'POKé DOLL',
    0x34: 'FULL HEAL',
    0x35: 'REVIVE',
    0x36: 'MAX REVIVE',
    0x37: 'GUARD SPEC',
    0x38: 'SUPER REPEL',
    0x39: 'MAX REPEL',
    0x3A: 'DIRE HIT',
    0x3B: 'COIN',
    0x3C: 'FRESH WATER',
    0x3D: 'SODA POP',
    0x3E: 'LEMONADE',
    0x3F: 'S.S. TICKET',
    0x40: 'GOLD TEETH',
    0x41: 'X ATTACK',
    0x42: 'X DEFEND',
    0x43: 'X SPEED',
    0x44: 'X SPECIAL',
    0x45: 'COIN CASE',
    0x46: "OAK's PARCEL",
    0x47: 'ITEMFINDER',
    0x48: 'SILPH SCOPE',
    0x49: 'POKé FLUTE',
    0x4A: 'LIFT KEY',
    0x4B: 'EXP.ALL',
    0x4C: 'OLD ROD',
    0x4D: 'GOOD ROD',
    0x4E: 'SUPER ROD',
    0x4F: 'PP UP',
    0x50: 'ETHER',
    0x51: 'MAX ETHER',
    0x52: 'ELIXER',
    0x53: 'MAX ELIXER',
};

export const MOVE_NAMES: Readonly<Record<number, string>> = {
    0x01: 'POUND',
    0x02: 'KARATE CHOP',
    0x03: 'DOUBLESLAP',
    0x04: 'COMET PUNCH',
    0x05: 'MEGA PUNCH',
    0x06: 'PAY DAY',
    0x07: 'FIRE PUNCH',
    0x08: 'ICE PUNCH',
    0x09: 'THUNDERPUNCH',
    0x0A: 'SCRATCH',
    0x0B: 'VICEGRIP',
    0x0C: 'GUILLOTINE',
    0x0D: 'RAZOR WIND',
    0x0E: 'SWORDS DANCE',
    0x0F: 'CUT',
    0x10: 'GUST',
    0x11: 'WING ATTACK',
    0x12: 'WHIRLWIND',
    0x13: 'FLY',
    0x14: 'BIND',
    0x15: 'SLAM',
    0x16: 'VINE WHIP',
    0x17: 'STOMP',
    0x18: 'DOUBLE KICK',
    0x19: 'MEGA KICK',
    0x1A: 'JUMP KICK',
    0x1B: 'ROLLING KICK',
    0x1C: 'SAND-ATTACK',
    0x1D: 'HEADBUTT',
    0x1E: 'HORN ATTACK',
    0x1F: 'FURY ATTACK',
    0x20: 'HORN DRILL',
    0x21: 'TACKLE',
    0x22: 'BODY SLAM',
    0x23: 'WRAP',
    0x24: 'TAKE DOWN',
    0x25: 'THRASH',
    0x26: 'DOUBLE-EDGE',
    0x27: 'TAIL WHIP',
    0x28: 'POISON STING',
    0x29: 'TWINEEDLE',
    0x2A: 'PIN MISSILE',
    0x2B: 'LEER',
    0x2C: 'BITE',
    0x2D: 'GROWL',
    0x2E: 'ROAR',
    0x2F: 'SING',
    0x30: 'SUPERSONIC',
    0x31: 'SONICBOOM',
    0x32: 'DISABLE',
    0x33: 'ACID',
    0x34: 'EMBER',
    0x35: 'FLAMETHROWER',
    0x36: 'MIST',
    0x37: 'WATER GUN',
    0x38: 'HYDRO PUMP',
    0x39: 'SURF',
    0x3A: 'ICE BEAM',
    0x3B: 'BLIZZARD',
    0x3C: 'PSYBEAM',
    0x3D: 'BUBBLEBEAM',
    0x3E: 'AURORA BEAM',
    0x3F: 'HYPER BEAM',
    0x40: 'PECK',
    0x41: 'DRILL PECK',
    0x42: 'SUBMISSION',
    0x43: 'LOW KICK',
    0x44: 'COUNTER',
    0x45: 'SEISMIC TOSS',
    0x46: 'STRENGTH',
    0x47: 'ABSORB',
    0x48: 'MEGA DRAIN',
    0x49: 'LEECH SEED',
    0x4A: 'GROWTH',
    0x4B: 'RAZOR LEAF',
    0x4C: 'SOLARBEAM',
    0x4D: 'POISONPOWDER',
    0x4E: 'STUN SPORE',
    0x4F: 'SLEEP POWDER',
    0x50: 'PETAL DANCE',
    0x51: 'STRING SHOT',
    0x52: 'DRAGON RAGE',
    0x53: 'FIRE SPIN',
    0x54: 'THUNDERSHOCK',
    0x55: 'THUNDERBOLT',
    0x56: 'THUNDER WAVE',
    0x57: 'THUNDER',
    0x58: 'ROCK THROW',
    0x59: 'EARTHQUAKE',
    0x5A: 'FISSURE',
    0x5B: 'DIG',
    0x5C: 'TOXIC',
    0x5D: 'CONFUSION',
    0x5E: 'PSYCHIC',
    0x5F: 'HYPNOSIS',
    0x60: 'MEDITATE',
    0x61: 'AGILITY',
    0x62: 'QUICK ATTACK',
    0x63: 'RAGE',
    0x64: 'TELEPORT',
    0x65: 'NIGHT SHADE',
    0x66: 'MIMIC',
    0x67: 'SCREECH',
    0x68: 'DOUBLE TEAM',
    0x69: 'RECOVER',
    0x6A: 'HARDEN',
    0x6B: 'MINIMIZE',
    0x6C: 'SMOKESCREEN',
    0x6D: 'CONFUSE RAY',
    0x6E: 'WITHDRAW',
    0x6F: 'DEFENSE CURL',
    0x70: 'BARRIER',
    0x71: 'LIGHT SCREEN',
    0x72: 'HAZE',
    0x73: 'REFLECT',
    0x74: 'FOCUS ENERGY',
    0x75: 'BIDE',
    0x76: 'METRONOME',
    0x77: 'MIRROR MOVE',
    0x78: 'SELFDESTRUCT',
    0x79: 'EGG BOMB',
    0x7A: 'LICK',
    0x7B: 'SMOG',
    0x7C: 'SLUDGE',
    0x7D: 'BONE CLUB',
    0x7E: 'FIRE BLAST',
    0x7F: 'WATERFALL',
    0x80: 'CLAMP',
    0x81: 'SWIFT',
    0x82: 'SKULL BASH',
    0x83: 'SPIKE CANNON',
    0x84: 'CONSTRICT',
    0x85: 'AMNESIA',
    0x86: 'KINESIS',
    0x87: 'SOFTBOILED',
    0x88: 'HI JUMP KICK',
    0x89: 'GLARE',
    0x8A: 'DREAM EATER',
    0x8B: 'POISON GAS',
    0x8C: 'BARRAGE',
    0x8D: 'LEECH LIFE',
    0x8E: 'LOVELY KISS',
    0x8F: 'SKY ATTACK',
    0x90: 'TRANSFORM',
    0x91: 'BUBBLE',
    0x92: 'DIZZY PUNCH',
    0x93: 'SPORE',
    0x94: 'FLASH',
    0x95: 'PSYWAVE',
    0x96: 'SPLASH',
    0x97: 'ACID ARMOR',
    0x98: 'CRABHAMMER',
    0x99: 'EXPLOSION',
    0x9A: 'FURY SWIPES',
    0x9B: 'BONEMERANG',
    0x9C: 'REST',
    0x9D: 'ROCK SLIDE',
    0x9E: 'HYPER FANG',
    0x9F: 'SHARPEN',
    0xA0: 'CONVERSION',
    0xA1: 'TRI ATTACK',
    0xA2: 'SUPER FANG',
    0xA3: 'SLASH',
    0xA4: 'SUBSTITUTE',
    0xA5: 'STRUGGLE',
};

export const TYPE_NAMES: Readonly<Record<number, string>> = {
    0x00: 'NORMAL',
    0x01: 'FIGHTING',
    0x02: 'FLYING',
    0x03: 'POISON',
    0x04: 'GROUND',
    0x05: 'ROCK',
    0x07: 'BUG',
    0x08: 'GHOST',
    0x14: 'FIRE',
    0x15: 'WATER',
    0x16: 'GRASS',
    0x17: 'ELECTRIC',
    0x18: 'PSYCHIC',
    0x19: 'ICE',
    0x1A: 'DRAGON',
};

export const SPRITE_NAMES: Readonly<Record<number, string>> = {
    0x01: '[player]',
    0x02: '[rival]',
    0x03: 'Oak',
    0x04: 'Youngster',
    0x05: 'Pokémon',
    0x06: 'Cool Trainer F',
    0x07: 'Cool Trainer M',
    0x08: 'Little Girl',
    0x09: 'Bird',
    0x0A: 'Middle Aged Man',
    0x0B: 'Gambler',
    0x0C: 'Super Nerd',
    0x0D: 'Girl',
    0x0E: 'Hiker',
    0x0F: 'Beauty',
    0x10: 'Gentleman',
    0x11: 'Daisy',
    0x12: 'Biker',
    0x13: 'Sailor',
    0x14: 'Cook',
    0x15: 'Bike Shop Clerk',
    0x16: 'Mr. Fuji',
    0x17: 'Giovanni',
    0x18: 'Rocket',
    0x19: 'Channeler',
    0x1A: 'Waiter',
    0x1B: 'Female Worker',
    0x1C: 'Middle Aged Woman',
    0x1D: 'Brunette Girl',
    0x1E: 'Lance',
    0x20: 'Scientist',
    0x21: 'Rocker',
    0x22: 'Swimmer',
    0x23: 'Safari Zone Worker',
    0x24: 'Gym Guide',
    0x25: 'Gramps',
    0x26: 'Clerk',
    0x27: 'Fishing Guru',
    0x28: 'Granny',
    0x29: 'Nurse',
    0x2A: 'Link Receptionist',
    0x2B: 'Male Worker',
    0x2C: 'Silph Worker',
    0x2D: 'Warden',
    0x2E: 'Captain',
    0x2F: 'Fisher',
    0x30: 'Koga',
    0x31: 'Guard',
    0x33: 'Mom',
    0x34: 'Balding Guy',
    0x35: 'Little Boy',
    0x37: 'Gameboy Kid',
    0x38: 'Fairy',
    0x39: 'Agata',
    0x3A: 'Bruno',
    0x3B: 'Lorelei',
    0x3C: 'Seel',
    0x3D: 'Poké Ball',
    0x3E: 'Fossil',
    0x3F: 'Boulder',
    0x40: 'Paper',
    0x41: 'Pokédex',
    0x42: 'Clipboard',
    0x43: 'Snorlax',
    0x45: 'Old Amber',
    0x48: 'Sleepy Old Man',
};

export const INTERNAL_SPECIES_NAMES: Readonly<Record<number, string>> = {
    0x01: 'RHYDON',
    0x02: 'KANGASKHAN',
    0x03: 'NIDORAN_M',
    0x04: 'CLEFAIRY',
    0x05: 'SPEAROW',
    0x06: 'VOLTORB',
    0x07: 'NIDOKING',
    0x08: 'SLOWBRO',
    0x09: 'IVYSAUR',
    0x0A: 'EXEGGUTOR',
    0x0B: 'LICKITUNG',
    0x0C: 'EXEGGCUTE',
    0x0D: 'GRIMER',
    0x0E: 'GENGAR',
    0x0F: 'NIDORAN_F',
    0x10: 'NIDOQUEEN',
    0x11: 'CUBONE',
    0x12: 'RHYHORN',
    0x13: 'LAPRAS',
    0x14: 'ARCANINE',
    0x15: 'MEW',
    0x16: 'GYARADOS',
    0x17: 'SHELLDER',
    0x18: 'TENTACOOL',
    0x19: 'GASTLY',
    0x1A: 'SCYTHER',
    0x1B: 'STARYU',
    0x1C: 'BLASTOISE',
    0x1D: 'PINSIR',
    0x1E: 'TANGELA',
    0x21: 'GROWLITHE',
    0x22: 'ONIX',
    0x23: 'FEAROW',
    0x24: 'PIDGEY',
    0x25: 'SLOWPOKE',
    0x26: 'KADABRA',
    0x27: 'GRAVELER',
    0x28: 'CHANSEY',
    0x29: 'MACHOKE',
    0x2A: 'MR_MIME',
    0x2B: 'HITMONLEE',
    0x2C: 'HITMONCHAN',
    0x2D: 'ARBOK',
    0x2E: 'PARASECT',
    0x2F: 'PSYDUCK',
    0x30: 'DROWZEE',
    0x31: 'GOLEM',
    0x33: 'MAGMAR',
    0x35: 'ELECTABUZZ',
    0x36: 'MAGNETON',
    0x37: 'KOFFING',
    0x39: 'MANKEY',
    0x3A: 'SEEL',
    0x3B: 'DIGLETT',
    0x3C: 'TAUROS',
    0x40: 'FARFETCHD',
    0x41: 'VENONAT',
    0x42: 'DRAGONITE',
    0x46: 'DODUO',
    0x47: 'POLIWAG',
    0x48: 'JYNX',
    0x49: 'MOLTRES',
    0x4A: 'ARTICUNO',
    0x4B: 'ZAPDOS',
    0x4C: 'DITTO',
    0x4D: 'MEOWTH',
    0x4E: 'KRABBY',
    0x52: 'VULPIX',
    0x53: 'NINETALES',
    0x54: 'PIKACHU',
    0x55: 'RAICHU',
    0x58: 'DRATINI',
    0x59: 'DRAGONAIR',
    0x5A: 'KABUTO',
    0x5B: 'KABUTOPS',
    0x5C: 'HORSEA',
    0x5D: 'SEADRA',
    0x60: 'SANDSHREW',
    0x61: 'SANDSLASH',
    0x62: 'OMANYTE',
    0x63: 'OMASTAR',
    0x64: 'JIGGLYPUFF',
    0x65: 'WIGGLYTUFF',
    0x66: 'EEVEE',
    0x67: 'FLAREON',
    0x68: 'JOLTEON',
    0x69: 'VAPOREON',
    0x6A: 'MACHOP',
    0x6B: 'ZUBAT',
    0x6C: 'EKANS',
    0x6D: 'PARAS',
    0x6E: 'POLIWHIRL',
    0x6F: 'POLIWRATH',
    0x70: 'WEEDLE',
    0x71: 'KAKUNA',
    0x72: 'BEEDRILL',
    0x74: 'DODRIO',
    0x75: 'PRIMEAPE',
    0x76: 'DUGTRIO',
    0x77: 'VENOMOTH',
    0x78: 'DEWGONG',
    0x7B: 'CATERPIE',
    0x7C: 'METAPOD',
    0x7D: 'BUTTERFREE',
    0x7E: 'MACHAMP',
    0x80: 'GOLDUCK',
    0x81: 'HYPNO',
    0x82: 'GOLBAT',
    0x83: 'MEWTWO',
    0x84: 'SNORLAX',
    0x85: 'MAGIKARP',
    0x88: 'MUK',
    0x8A: 'KINGLER',
    0x8B: 'CLOYSTER',
    0x8D: 'ELECTRODE',
    0x8E: 'CLEFABLE',
    0x8F: 'WEEZING',
    0x90: 'PERSIAN',
    0x91: 'MAROWAK',
    0x93: 'HAUNTER',
    0x94: 'ABRA',
    0x95: 'ALAKAZAM',
    0x96: 'PIDGEOTTO',
    0x97: 'PIDGEOT',
    0x98: 'STARMIE',
    0x99: 'BULBASAUR',
    0x9A: 'VENUSAUR',
    0x9B: 'TENTACRUEL',
    0x9D: 'GOLDEEN',
    0x9E: 'SEAKING',
    0xA3: 'PONYTA',
    0xA4: 'RAPIDASH',
    0xA5: 'RATTATA',
    0xA6: 'RATICATE',
    0xA7: 'NIDORINO',
    0xA8: 'NIDORINA',
    0xA9: 'GEODUDE',
    0xAA: 'PORYGON',
    0xAB: 'AERODACTYL',
    0xAD: 'MAGNEMITE',
    0xB0: 'CHARMANDER',
    0xB1: 'SQUIRTLE',
    0xB2: 'CHARMELEON',
    0xB3: 'WARTORTLE',
    0xB4: 'CHARIZARD',
    0xB9: 'ODDISH',
    0xBA: 'GLOOM',
    0xBB: 'VILEPLUME',
    0xBC: 'BELLSPROUT',
    0xBD: 'WEEPINBELL',
    0xBE: 'VICTREEBEL',
};

export const POKEDEX_SPECIES_NAMES: readonly string[] = [
    '', // 0-indexed placeholder
    'BULBASAUR', 'IVYSAUR', 'VENUSAUR', 'CHARMANDER', 'CHARMELEON', 'CHARIZARD',
    'SQUIRTLE', 'WARTORTLE', 'BLASTOISE', 'CATERPIE', 'METAPOD', 'BUTTERFREE',
    'WEEDLE', 'KAKUNA', 'BEEDRILL', 'PIDGEY', 'PIDGEOTTO', 'PIDGEOT',
    'RATTATA', 'RATICATE', 'SPEAROW', 'FEAROW', 'EKANS', 'ARBOK',
    'PIKACHU', 'RAICHU', 'SANDSHREW', 'SANDSLASH', 'NIDORAN_F', 'NIDORINA',
    'NIDOQUEEN', 'NIDORAN_M', 'NIDORINO', 'NIDOKING', 'CLEFAIRY', 'CLEFABLE',
    'VULPIX', 'NINETALES', 'JIGGLYPUFF', 'WIGGLYTUFF', 'ZUBAT', 'GOLBAT',
    'ODDISH', 'GLOOM', 'VILEPLUME', 'PARAS', 'PARASECT', 'VENONAT',
    'VENOMOTH', 'DIGLETT', 'DUGTRIO', 'MEOWTH', 'PERSIAN', 'PSYDUCK',
    'GOLDUCK', 'MANKEY', 'PRIMEAPE', 'GROWLITHE', 'ARCANINE', 'POLIWAG',
    'POLIWHIRL', 'POLIWRATH', 'ABRA', 'KADABRA', 'ALAKAZAM', 'MACHOP',
    'MACHOKE', 'MACHAMP', 'BELLSPROUT', 'WEEPINBELL', 'VICTREEBEL', 'TENTACOOL',
    'TENTACRUEL', 'GEODUDE', 'GRAVELER', 'GOLEM', 'PONYTA', 'RAPIDASH',
    'SLOWPOKE', 'SLOWBRO', 'MAGNEMITE', 'MAGNETON', 'FARFETCHD', 'DODUO',
    'DODRIO', 'SEEL', 'DEWGONG', 'GRIMER', 'MUK', 'SHELLDER',
    'CLOYSTER', 'GASTLY', 'HAUNTER', 'GENGAR', 'ONIX', 'DROWZEE',
    'HYPNO', 'KRABBY', 'KINGLER', 'VOLTORB', 'ELECTRODE', 'EXEGGCUTE',
    'EXEGGUTOR', 'CUBONE', 'MAROWAK', 'HITMONLEE', 'HITMONCHAN', 'LICKITUNG',
    'KOFFING', 'WEEZING', 'RHYHORN', 'RHYDON', 'CHANSEY', 'TANGELA',
    'KANGASKHAN', 'HORSEA', 'SEADRA', 'GOLDEEN', 'SEAKING', 'STARYU',
    'STARMIE', 'MR_MIME', 'SCYTHER', 'JYNX', 'ELECTABUZZ', 'MAGMAR',
    'PINSIR', 'TAUROS', 'MAGIKARP', 'GYARADOS', 'LAPRAS', 'DITTO',
    'EEVEE', 'VAPOREON', 'JOLTEON', 'FLAREON', 'PORYGON', 'OMANYTE',
    'OMASTAR', 'KABUTO', 'KABUTOPS', 'AERODACTYL', 'SNORLAX', 'ARTICUNO',
    'ZAPDOS', 'MOLTRES', 'DRATINI', 'DRAGONAIR', 'DRAGONITE', 'MEWTWO',
    'MEW',
];

export const RED_BLUE_TITLES = new Set([
    'POKEMON RED',
    'POKEMON RED VERSION',
    'POKEMON BLUE',
    'POKEMON BLUE VERSION',
    'POKEMON BLU',
    'POKEMON_RED',
    'POKEMON_BLUE',
    'POKEMON RED (USA, EUROPE)',
    'POKEMON BLUE (USA, EUROPE)',
    'POKEMON RED (UE)',
    'POKEMON BLUE (UE)',
    'POKEMON RED (E)',
    'POKEMON BLUE (E)',
    'POKEMON RED (J)',
    'POKEMON BLUE (J)',
    'POKEMON RED (JAPAN)',
    'POKEMON BLUE (JAPAN)',
    'POKEMON AKAB',
    'POKEMON AO',
]);

export const RED_BLUE_GAME_CODES = new Set([
    'APSE', // Red USA
    'APAE', // Blue USA
    'APSD', // Red German
    'APAD', // Blue German
    'APSF', // Red French
    'APAF', // Blue French
    'APSS', // Red Spanish
    'APAS', // Blue Spanish
    'APSI', // Red Italian
    'APAI', // Blue Italian
    'APAJ', // Blue Japan
    'APSJ', // Red Japan
]);

export function isPokemonRedBlue(title: string, gameCode?: string): boolean {
    const cleanTitle = title.trim().toUpperCase();
    const cleanCode = (gameCode ?? '').trim().toUpperCase();

    if (
        cleanTitle.includes('YELLOW') ||
        cleanTitle.includes('GOLD') ||
        cleanTitle.includes('SILVER') ||
        cleanTitle.includes('CRYSTAL') ||
        cleanTitle.includes('PINBALL') ||
        cleanTitle.includes('FIRE') ||
        cleanTitle.includes('LEAF') ||
        cleanTitle.includes('RUBY') ||
        cleanTitle.includes('SAPPHIRE') ||
        cleanTitle.includes('EMERALD')
    ) {
        return false;
    }

    if (cleanCode && RED_BLUE_GAME_CODES.has(cleanCode)) return true;
    if (cleanTitle && RED_BLUE_TITLES.has(cleanTitle)) return true;
    if (cleanTitle.startsWith('POKEMON BLUE') || cleanTitle.startsWith('POKEMON RED') || cleanTitle.startsWith('POKEMON BLU')) return true;

    return false;
}
